---
- name: Download WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no 

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ item.folder }}"
    copy: no
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: 0750
  with_items: "{{ wp }}"

- name: Copy config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.folder }}/wordpress/wp-config.php"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: 0750
  with_items: "{{ wp }}"